sonar.projectKey=mi-app-segura
sonar.projectName=mi-app-segura
sonar.projectVersion=3.0.0
sonar.sources=.
sonar.exclusions=node_modules/**, .git/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.organization=devyaelmartinez
